language: python
dist: xenial

matrix:
  fast_finish: true
  include:
    - python: 3.7
    - python: 3.8-dev
    - python: nightly
  allow_failures:
    - python: nightly

script:
    - pip install --upgrade pip setuptools
    - pip install .
    - pypi_stats

notifications:
  irc:
    channels:
      - "chat.freenode.net#bandersnatch"

cache:
    directories:
        - $HOME/.cache/pip
